### PR TITLE
I think I finished the weekend homework

### PR DESCRIPTION
**Pull request by daherr**
I added all the search methods, I think I did all of the properly.

### CODE REVIEW

**Comment by daherr** [comment]
Well I'm stuck at the sort by priority. I'm fairly certain I know what I'm supposed to do, I'm sure how to di it though. I think I'm supposed to use the .sort() method in array list because it would do the sorting for me which would be nice, and it's convenient. To do I would need it to sort by the number associated with the priority, however, the .sort() is saying that the t.getPriority is Boolean and therefore cannot be used as comparators to sort by. I have also tried t.setPriority thinking I had the wrong method, however, this also did not work. Another issue I see is that in my comparison statement, that should not work, so also if I was to figure the first part out, how would I index the priorities to go up, with the tasks, so I don't get the same results. Thanks!
David

**Comment by jwoytek** [comment]
That's a lot to think about on a Sunday evening. How about if we say,
"don't worry about it for now" and we will take a look at things tomorrow.
Sound good?

Jonathan

**Comment by daherr** [comment]
oh ok, that's perfectly fine, I didn't know if I had to finish this tonight, thanks! that makes my life a whole lot easier! Thanks again!

**Comment by daherr** [comment]
Ok, so I'm working on my homework again, and yeah I cannot for  the life of me figure out this .sort line, I paid attention in class, but I didn't really understand much of it, I have to compare to method, but I don't know how to implement it, also what is super and E, and how do I properly use them? I'm sorry that I do not understand this that much, and I have a feeling I'm just missing or forgetting something all together, but I do want to finish this on time for full credit

**Comment by jwoytek** [comment]
You need to implement compareTo inside Task for sort to work. In addition
to what we did in class, there are a lot of good examples online. You don't
use super anywhere (yet), and I don't know what "E" is. If you are seeing
things that use super, you're probably looking in the wrong place.

It sounds like you are getting close. Google around and look for some
tutorials or examples of Collections.sort.

**Comment by daherr** [comment]
I finished the sorter only to find out that my file writer does not even come close to working, I don't know how this got past me for so long, but it did, and I don't know how to fix it, my writer only saves the last entered task and deletes the rest, I'm probably missing something small and stupid, but for the life of me, I cannot get this darn thing to work, and the more I work on it, the more frustrated, tired, and depressed I get. Even so, I understand why the sorter works, but I am totally lost with the syntax of it. I understand this will most likely cost me a potion of my grade on an assignment that should have been fairly easy, but I have spent a lot of time today working through the program and the problems I run into with it. I will most likely talk to you about it tomorrow if possible, but my parents are not giving me anymore time tonight to work on it, and I need to get to bed.

**Comment by daherr** [comment]
So it looks like I'm starting the semester at a rip roaring pace

**Comment by daherr** [comment]
Well haha, I finally finished... Only a day late... but I have a somewhat decent understanding of what went wrong and why, and as usual it was one singular line of code that screwed up the whole program, thank you for your patience!
David

**Comment by jwoytek** [comment]
No problem at all. I know it is sometimes painful when I say you have to
figure it out on your own, but that is what builds understanding of complex
subjects!

Jonathan

On Tuesday, February 2, 2016, daherr <notifications@github.com> wrote:

> Well haha, I finally finished... Only a day late... but I have a somewhat
> decent understanding of what went wrong and why, and as usual it was one
> singular line of code that screwed up the whole program, thank you for your
> patience!
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SJHS-CS0501/TaskManager/pull/3#issuecomment-178961382>
> .
>


-- 
Sent from my Commodore64

**Pull request closed without merging**
